components_manager:
    components:                       # Configuring components that were registered via component_list
        auth-database:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            dns_resolver: async

        auth-pg-cache:
            pgcomponent: auth-database
            update-interval: 10s

        handler-get-for-moderation:
            path: /v1/get-for-moderation
            task_processor: main-task-processor
            method: GET
            auth:
                types:
                  - bearer
                scopes:
                  - Moderator

        handler-delete-from-moderation:
            path: /v1/delete-from-moderation
            task_processor: main-task-processor
            method: DELETE
            auth:
                types:
                  - bearer
                scopes:
                  - Moderator

        handler-add-obj:
            path: /v1/add-obj
            task_processor: main-task-processor
            method: POST
            auth:
                types:
                  - bearer
                scopes:
                  - Moderator

        testsuite-support:

        server:
            listener:                 # configuring the main listening socket...
                port: 8095            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: $log_file_path
                    level: warning
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        dns-client:
            fs-task-processor: fs-task-processor

    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: 4         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: 4

    default_task_processor: main-task-processor  # Task processor in which components start.